---
version: "2.1"
services:
  ddns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: ddns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SUBDOMAINS=SUBDOMAIN.duckdns.org
      - TOKEN=API_TOKEN
      - LOG_FILE=false
    volumes:
      - ./config:/config
