---
version: "2.1"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      #- 8080:8080 # Dashboard port

    volumes:
      - ./config/:/config/
      - ./etc/:/etc/traefik/
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`SUBDOMAIN.duckdns.org`)
      traefik.http.routers.api.entryPoints: https
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: api-auth
      traefik.http.middlewares.api-auth.basicauth.users: "AUTH_STR"
      traefik.http.middlewares.api-auth.basicauth.removeheader: true
    environment:
      DOCKER_HOST: dockersocket
      DUCKDNS_TOKEN:  DUCKDNS_TOKEN
    depends_on:
      - dockersocket

  dockersocket:
    image: tecnativa/docker-socket-proxy
    container_name: dockersocket
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/config/
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0

  whoami:
    image: traefik/whoami:latest
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.mywhoami.rule: Host(`whoami.SUBDOMAIN.duckdns.org`)
      traefik.http.routers.mywhoami.entryPoints: https
      traefik.http.routers.mywhoami.middlewares: mywhoami-auth
      traefik.http.middlewares.mywhoami-auth.basicauth.users: "AUTH_STR"
      traefik.http.middlewares.mywhoami-auth.basicauth.removeheader: true

  #photoprism:
  #  image: photoprism/photoprism:latest
  #  restart: unless-stopped
  #  networks:
  #    - proxy
  #  labels:
  #    traefik.enable: true
  #    traefik.http.routers.photoprism.rule: Host(`photoprism.SUBDOMAIN.duckdns.org`)
  #    traefik.http.routers.photoprism.entryPoints: https
  #    #traefik.http.routers.api.service: api@internal
  #    traefik.http.routers.photoprism.middlewares: photoprism-auth
  #    traefik.http.middlewares.photoprism-auth.basicauth.users: "AUTH_STR"
  #    traefik.http.middlewares.photoprism-auth.basicauth.removeheader: true
  #    #traefik.http.routers.photoprism.tls: true
  #    #traefik.http.routers.photoprism.tls.certresolver: letsencrypt
  #  volumes:
  #    - "./originals:/photoprism/originals"
  #    - "./storage:/photoprism/storage"
  #  environment:
  #    PHOTOPRISM_SITE_URL: "https://photoprism.SUBDOMAIN.duckdns.org"
  #    PHOTOPRISM_ADMIN_PASSWORD: "PHOTOPRISM_ADMIN_PASSWORD"

networks:
  proxy:
    driver: bridge
    external: true
